# Generated by Django 3.2.15 on 2023-10-28 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231025_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='В имени использованы запрещенные символы', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
