# Generated by Django 3.2.15 on 2023-10-29 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribes',
            field=models.ManyToManyField(related_name='subscribed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
