# Generated by Django 3.2.15 on 2023-10-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_subscribes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribes',
        ),
    ]
